language: php

php:
  - '7.1'
  - '7.2'

env:
  global:
    - APP_ENV=test

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

scripts:
  - ./bin/phpunit